### ISSUE TITLE
Crash on load [Linux/Wine]

### ISSUE THREAD

**Issue by riolubruh** [GerardS0406/BO2-Cold-War-Mod#1]
Not sure why this happens. Here's the crash log.
[crashdumps.zip](https://github.com/GerardS0406/BO2-Cold-War-Mod/files/9081254/crashdumps.zip)

**Comment by GerardS0406** [comment]
I wouldn't know anything about running on Linux/Wine.
Also did this happen in game? Or did it happen loading up plutonium?

**Comment by riolubruh** [comment]
It happens during loading of any zombies map in solo/custom games.
