### ISSUE TITLE
No place in HUD to see which part(s) you are carrying

### ISSUE THREAD

**Issue by riolubruh** [GerardS0406/BO2-Cold-War-Mod#2]
Technically not a bug, more of a feature request.
Not being able to see what you are carrying can make it a little more difficult to build things.

**Comment by GerardS0406** [comment]
As stated, the mod is at the HUD limit, there's no way to show these things at this point.

**Comment by riolubruh** [comment]
Ah, sorry, I wasn't aware, I wouldn't have made an issue if I had known.

**Comment by riolubruh** [comment]
Would it be possible if you used the original HUD element?
Like If you made the regular HUD 'visible' (i.e. changing hud_enable to 1) but then used some textures (or maybe you could use dvars, like hud_hardcore/ui_hud_hardcore?), then theoretically all you would have to do would be to move the weapon name/rarity/ammo counter up by a few pixels to make sure the part doesn't overlap.
I don't really know how it all works on BO2 but I hope the suggestion is at least a little helpful -_-
(I know more about how shit works on WAW so like on waw ui_hud_hardcore or similar would work for this but not necessarily on bo2) 

I tried to do it with texture modifying cause I couldn't get it to work the way I wanted using cw_hud.gsc except one time where I somehow accidentally figured out a way to put the hud into 'hardcore mode' (aka no vanilla hud except for a kind of strange-looking floating ammo counter) but it must have been a fluke because I can't recreate it -.- ... 
here's all I got that I can actually prove happened :/
![f](https://user-images.githubusercontent.com/54255074/179349875-f330828c-b049-4fcd-aee9-58da0da605c6.png)

**Comment by riolubruh** [comment]
Just saw the new version! Nice work as always, Gerard! :o 
I'm not even gonna try to understand how you do it XD
