### ISSUE TITLE
Mule Kick Ammo Refill with Time Bombs

### ISSUE THREAD

**Issue by riolubruh** [GerardS0406/BO2-Cold-War-Mod#3]
Steps to reproduce:
1. Get Time Bomb and Mule Kick
2. Kill zombies until a clip appears
3. Equip Time Bomb
4. Throw a time bomb (so that you have 0 / 0)
5. Grab clip(s)
6. You now have extra (non-functional) time bombs that you should not be able to get
![zmshot0001](https://user-images.githubusercontent.com/54255074/179388167-13638cc9-e3fa-4331-9a61-6cce2555cdec.jpg)
(ignore the hud)

Honestly I think it would be super cool if you could actually refill the time bomb like this (like the same way a max ammo would so it would actually let you re-save the current game state). It would be kinda broken but whatever lol.

**Expected Behavior:** That the mule kick clips would never refill ammo while the time bomb is the current weapon.

**Comment by GerardS0406** [comment]
Time Bombs received a complete overhaul in the next update. Be sure to check out the patch notes.
