### ISSUE TITLE
[Regression] PaPed Weapons without a specified Level are no longer assumed as "Level 1"

### ISSUE THREAD

**Issue by riolubruh** [GerardS0406/BO2-Cold-War-Mod#4]
There are likely multiple non-cheat ways this can happen.
One way is the following:
1. Place an upgraded weapon into the locker.
2. Leave match / end game and start a new game.
3. Take the weapon out of the locker

_Note: I do NOT expect the weapon to retain its' Level through games. That is likely impossible; HOWEVER,_

This is what happens when you take an upgraded weapon out of the locker:
![image](https://user-images.githubusercontent.com/54255074/179389310-a78b4df4-f29f-495d-8b7c-2e68be47e38c.png)
The weapon is pack-a-punched, however it is not "leveled". In this case, it should be a Level 1 WN.

**Previously,** Level was **assumed to be Level 1** if you obtained an upgraded weapon that did not have a "Level".

**Currently,** it seems that the Level remains as undefined, despite the being upgraded at least once since it is an 'upgraded' weapon and therefore should have a minimum of "Level 1".

This will cause multiple problems when attempting to re-pack.
If you have a weapon without a specified Level, and attempt to pack-a-punch, the following will happen:
On the 1st Pack with a 'Level-less' PaPed weapon, 5000 points are taken, and an attachment is modified (like how BO2's vanilla re-packing normally gives you a sight or changes the attachment, except it costs 5000 instead of 2000). Your weapon now is "Level 1".
Each subsequent pack-a-punch works as expected, however there is no way to change which sight/attachment was put on the weapon.

Furthermore, there should be a way to modify which attachment is on your weapon just like vanilla BO2. (Especially if you have already gotten Level 3 on your weapon and want an extended mag or grip or whatever).

**Solution/Expected behavior:** IF current_weapon_name includes "upgraded" && (Level == undefined OR Level == 0), Level == 1.

**Comment by GerardS0406** [comment]
It was never assumed, it just depended on if you had that weapon previously. It has been fixed in the next update.

**Comment by GerardS0406** [comment]
Attachments can now be changed via Salvage Bench (after PaP)
