### ISSUE TITLE
Double Death with Tombstone Issue

### ISSUE THREAD

**Issue by riolubruh** [GerardS0406/BO2-Cold-War-Mod#5]
If you down with Tombstone, then repurchase it while being a ghost, then bleed out, you are believed to be dead by the mod so it does the Tombstone effect on your ghost and forces you into prone constantly and makes you ignored.
Basically, die as a ghost with Tombstone.
This results in the mod forcing you into prone constantly and all zombies will ignore you until you reverse it.
Steps to reproduce:
1. Get tombstone
2. Down
3. Get tombstone while being a ghost
4. Bleed out

You can escape from it by rebuying Tombstone and then using Aether Shroud to reset your ignoreme flag to false; then you can let yourself down again so you can revive yourself again and therefore reverse the glitched flags.
(Aether Shroud probably isn't necessary but if you don't have it you need to find another way to down that doesn't involve zombies.)

Honestly I have no idea what the intended behavior should be. On one hand, if you have Tombstone as a ghost and you bleed out, you would become a ghost of your ghost (which makes no sense). On the other hand, just dying would be kind of suckish because you can't really tell how much time you have to revive yourself (which is how I actually discovered the glitch, lol).

Either way, it's a glitch that makes you invisible until you manually reverse it with Aether Shroud and/or a suicide with tombstone to reset the broken flags. (if you don't have Aether Shroud while also having PHD you have to find another way to kill yourself, luckily almost every bo2 map lets you do this with traps/deathpits/etc.)

**Comment by GerardS0406** [comment]
Been fixed but it may not release for a few days. I'm trying to work on the BO1 version as much as possible haha. And I have work this weekend. You will not be able to buy perks while in tombstone mode.
